CREATE TABLE IF NOT EXISTS users (
    id_user SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS approved_users (
    id_approved_users SERIAL PRIMARY KEY,
    id_user INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);